# Use root/example as user/password credentials
version: '3.1'

services:

  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
      POSTGRES_DB: cadastro
    ports:
      - 5432:5432
